exp_id: debug
tasks: close_jar
bs: 4
num_workers: 3
epochs: 2       #10
train_iter: 12800    #160000
save_every_n_epochs: 2   # >0: save every N epochs (skip epoch 0) + final epoch; 0: disable saving
sample_distribution_mode: task_uniform
wandb_project: "bridgevla_sam"
wandb_run: "test"
log_dir: "/robot/robot-research-exp-0/user/lpy/BridgeVLA_sam/data/bridgevla_data/logs"
peract:
  lr: 8e-5 # 
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
rvt:
  place_with_mean: False
  img_aug: 0.0
